version: "1"
services:
  - type: web
    name: farmaid-backend
    runtime: node
    repo: https://github.com/Sephatodi/Final-year-Project
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_cz60hFdAqpgU@ep-lively-feather-anwhkvck-pooler.c-6.us-east-1.aws.neon.tech/FarmAid?sslmode=require&channel_binding=require
      - key: FRONTEND_URL
        value: https://final-year-project-blond-two.vercel.app

  - type: web
    name: farmaid-couchdb
    runtime: docker
    repo: https://github.com/Sephatodi/Final-year-Project
    plan: free
    region: oregon
    dockerContext: couchdb
    dockerfilePath: couchdb/Dockerfile
    envVars:
      - key: COUCHDB_USER
        value: admin
      - key: COUCHDB_PASSWORD
        value: password123
